# Generated by Django 5.1 on 2024-08-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chatbot_App', '0003_alter_agent_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user_defined_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
