# Generated by Django 4.2.7 on 2026-01-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chatbot_App', '0005_chathistory_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cache_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
